In [1]:
#!/usr/bin/env python2
# -*- coding: utf-8 -*-


import datetime
test_start_date = datetime.datetime.now() - datetime.timedelta(days = 5)
test_end_date = datetime.datetime.now() #- datetime.timedelta(days = 4)



from newsapi import NewsAPI
key = '96af62a035db45bda517a9ca62a25ac3'
params = {}
api = NewsAPI(key)
sources = api.sources(params)
articles = api.articles(sources[0]['id'], params)
import sys, csv, json
#reload(sys)
#sys.setdefaultencoding('utf8')
import requests
"""
About:
Python wrapper for the New York Times Archive API 
https://developer.nytimes.com/article_search_v2.json
"""
class APIKeyException(Exception):
    def __init__(self, message): self.message = message 
class InvalidQueryException(Exception):
    def __init__(self, message): self.message = message 
class ArchiveAPI(object):
    def __init__(self, key=None):
        """
        Initializes the ArchiveAPI class. Raises an exception if no API key is given.
        :param key: New York Times API Key
        """
        self.key = key
        self.root = 'http://api.nytimes.com/svc/archive/v1/{}/{}.json?api-key={}' 
        if not self.key:
            nyt_dev_page = 'http://developer.nytimes.com/docs/reference/keys'
            exception_str = 'Warning: API Key required. Please visit {}'
            raise NoAPIKeyException(exception_str.format(nyt_dev_page))

    def query(self, year=None, month=None, key=None,):
        """
        Calls the archive API and returns the results as a dictionary.
        :param key: Defaults to the API key used to initialize the ArchiveAPI class.
        """
        if not key: key = self.key
        if (year < 1882) or not (0 < month < 13):
            # currently the Archive API only supports year >= 1882
            exception_str = 'Invalid query: See http://developer.nytimes.com/archive_api.json'
            raise InvalidQueryException(exception_str)
            
        url = self.root.format(year, month, key)
        r = requests.get(url)
        return r.json()


api = ArchiveAPI('0ba6dc04a8cb44e0a890c00df88c393a')

import datetime
now = datetime.datetime.now()
currentMonthStart=datetime.date.today().replace(day=1).strftime("%Y-%m-%d")
currentMonthStart
years = [now.year]
months = [now.month]


for year in years:
    for month in months:
        mydict = api.query(year, month)
        file_str = 'thisNews' + '.json'
        with open(file_str, 'w') as fout:
            json.dump(mydict, fout)
        fout.close()
currentDateNow=datetime.datetime.now().strftime("%Y-%m-%d")

In [ ]:
from googlefinance.client import get_price_data, get_prices_data, get_prices_time_data

# Dow Jones
param = {
    'q': ".GSPC", # Stock symbol (ex: "AAPL")
    'i': "86400", # Interval size in seconds ("86400" = 1 day intervals)
    'x': "INDEXDJX", # Stock exchange symbol on which stock is traded (ex: "NASD")
    'p': "1M" # Period (Ex: "1Y" = 1 year)
}
# get price data (return pandas dataframe)
df = get_price_data(param)
print(df)
df.to_csv('thisPriceGSPC.csv')

In [3]:
import numpy as np
import csv, json
import pandas as pd

################################################################################################
## Preparing DJIA data
# Reading DJIA index prices csv file
with open('thisPrice.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    # Converting the csv file reader to a lists 
    data_list = list(spamreader)

# Separating header from the data
header = data_list[0] 
data_list = data_list[1:] 

data_list = np.asarray(data_list)

# Selecting date and close value for each day
selected_data = data_list[:, [0, 4]]



df = pd.DataFrame(data=selected_data[0:,1:],
             index=selected_data[0:,0],
                                columns=['close'],
                                        dtype='float64')



df1 = df
idx = pd.date_range(currentMonthStart, currentDateNow)
df1.index = pd.DatetimeIndex(df1.index)
df1 = df1.reindex(idx, fill_value=np.NaN)
# df1.count() # gives 2518 count
interpolated_df = df.interpolate()
interpolated_df.count() # gives 3651 count

# Removing extra date rows added in data for calculating interpolation
interpolated_df = interpolated_df[3:]

date_format = ["%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%dT%H:%M:%S+%f"]
def try_parsing_date(text):
    for fmt in date_format:
        #return datetime.strptime(text, fmt)
        try:
            return datetime.strptime(text, fmt).strftime('%Y-%m-%d')
        except ValueError:
            pass
    raise ValueError('no valid date format found')


print ('### parsing date and price done##')



years = [now.year]
months = [now.month]
dict_keys = ['pub_date', 'headline'] #, 'lead_paragraph']
articles_dict = dict.fromkeys(dict_keys)
# Filtering list for type_of_material
type_of_material_list = ['blog', 'brief', 'news', 'editorial', 'op-ed', 'list','analysis']
# Filtering list for section_name
section_name_list = ['business', 'national', 'world', 'u.s.' , 'politics', 'opinion', 'tech', 'science',  'health']
news_desk_list = ['business', 'national', 'world', 'u.s.' , 'politics', 'opinion', 'tech', 'science',  'health', 'foreign']



from datetime import datetime
current_date = datetime.now().isoformat()

#years = [2015]
#months = [3]

current_article_str = ''      

## Adding article column to dataframe
interpolated_df["articles"] = ''
count_articles_filtered = 0
count_total_articles = 0
count_main_not_exist = 0               
count_unicode_error = 0     
count_attribute_error = 0   
for year in years:
    for month in months:
        file_str = 'thisNews' + '.json'
        with open(file_str) as data_file:    
            NYTimes_data = json.load(data_file)
        count_total_articles = count_total_articles + len(NYTimes_data["response"]["docs"][:])
        
        print ('Opening file:')
        print (str(year) + '-' + '{:02}'.format(month))
        
        for i in range(len(NYTimes_data["response"]["docs"][:])):
            try:
                if any(substring in NYTimes_data["response"]["docs"][:][i]['type_of_material'].lower() for substring in type_of_material_list):
                    if any(substring in NYTimes_data["response"]["docs"][:][i]['section_name'].lower() for substring in section_name_list):
                        #count += 1
                        count_articles_filtered += 1
                        #print 'i: ' + str(i)
                        articles_dict = { your_key: NYTimes_data["response"]["docs"][:][i][your_key] for your_key in dict_keys }
                        articles_dict['headline'] = articles_dict['headline']['main'] # Selecting just 'main' from headline
                        #articles_dict['headline'] = articles_dict['lead_paragraph'] # Selecting lead_paragraph
                        date = try_parsing_date(articles_dict['pub_date'])
                        #print 'article_dict: ' + articles_dict['headline']
                        if date == current_date:
                            current_article_str = current_article_str + '. ' + articles_dict['headline']
                        else:  
                            interpolated_df.set_value(current_date, 'articles', interpolated_df.loc[current_date, 'articles'] + '. ' + current_article_str)
                            current_date = date
                            #interpolated_df.set_value(date, 'articles', current_article_str)
                            #print str(date) + current_article_str
                            current_article_str = articles_dict['headline']
                        # For last condition in a year
                        if (date == current_date) and (i == len(NYTimes_data["response"]["docs"][:]) - 1): 
                            interpolated_df.set_value(date, 'articles', current_article_str)   
                        
             #Exception for section_name or type_of_material absent
            except AttributeError:
                #print 'attribute error'
                #print NYTimes_data["response"]["docs"][:][i]
                count_attribute_error += 1
                # If article matches news_desk_list if none section_name found
                try:
                    if any(substring in NYTimes_data["response"]["docs"][:][i]['news_desk'].lower() for substring in news_desk_list):
                            #count += 1
                            count_articles_filtered += 1
                            #print 'i: ' + str(i)
                            articles_dict = { your_key: NYTimes_data["response"]["docs"][:][i][your_key] for your_key in dict_keys }
                            articles_dict['headline'] = articles_dict['headline']['main'] # Selecting just 'main' from headline
                            #articles_dict['headline'] = articles_dict['lead_paragraph'] # Selecting lead_paragraph
                            date = try_parsing_date(articles_dict['pub_date'])
                            #print 'article_dict: ' + articles_dict['headline']
                            if date == current_date:
                                current_article_str = current_article_str + '. ' + articles_dict['headline']
                            else:  
                                interpolated_df.set_value(current_date, 'articles', interpolated_df.loc[current_date, 'articles'] + '. ' + current_article_str)
                                current_date = date
                                #interpolated_df.set_value(date, 'articles', current_article_str)
                                #print str(date) + current_article_str
                                current_article_str = articles_dict['headline']
                            # For last condition in a year
                            if (date == current_date) and (i == len(NYTimes_data["response"]["docs"][:]) - 1): 
                                interpolated_df.set_value(date, 'articles', current_article_str)   
                
                except AttributeError:
                    pass
                pass
            except KeyError:
                print ('key error')
                #print NYTimes_data["response"]["docs"][:][i]
                count_main_not_exist += 1
                pass   
            except TypeError:
                print ("type error")
                #print NYTimes_data["response"]["docs"][:][i]
                count_main_not_exist += 1
                pass
         

              
print (count_articles_filtered) 
print (count_total_articles)                     
print (count_main_not_exist)
print (count_unicode_error)



## Putting all articles if no section_name or news_desk not found
for date, row in interpolated_df.T.iteritems():   
    if len(interpolated_df.loc[date, 'articles']) <= 400:
        #print interpolated_df.loc[date, 'articles']
        #print date
        month = date.month
        year = date.year
        file_str = 'thisNews' + '.json'
        with open(file_str) as data_file:    
            NYTimes_data = json.load(data_file)
        count_total_articles = count_total_articles + len(NYTimes_data["response"]["docs"][:])
        interpolated_df.set_value(date.strftime('%Y-%m-%d'), 'articles', '')
        for i in range(len(NYTimes_data["response"]["docs"][:])):
            try:
                
                articles_dict = { your_key: NYTimes_data["response"]["docs"][:][i][your_key] for your_key in dict_keys }
                articles_dict['headline'] = articles_dict['headline']['main'] # Selecting just 'main' from headline
                #articles_dict['headline'] = articles_dict['lead_paragraph'] # Selecting lead_paragraph       
                pub_date = try_parsing_date(articles_dict['pub_date'])
                #print 'article_dict: ' + articles_dict['headline']
                if date.strftime('%Y-%m-%d') == pub_date: 
                    interpolated_df.set_value(pub_date, 'articles', interpolated_df.loc[pub_date, 'articles'] + '. ' + articles_dict['headline'])  
                
            except KeyError:
                print ('key error')
                #print NYTimes_data["response"]["docs"][:][i]
                #count_main_not_exist += 1
                pass   
            except TypeError:
                print ("type error")
                #print NYTimes_data["response"]["docs"][:][i]
                #count_main_not_exist += 1
                pass


#>>> print count_articles_filtered 
#440770
#>>> print count_total_articles 
#1073132


## Filtering the whole data for a year
#filtered_data = interpolated_df.ix['2016-01-01':'2016-12-31']
#filtered_data.to_pickle('/Users/Dinesh/Documents/Project Stock predictions/data/pickled_ten_year_all.pkl')  


# Saving the data as pickle file
interpolated_df.to_pickle('pickled_para.pkl')  


# Save pandas frame in csv form
interpolated_df.to_csv('sample_interpolated_para.csv',
                       sep='\t', encoding='utf-8')



# Reading the data as pickle file
dataframe_read = pd.read_pickle('pickled_para.pkl')

### parsing date and price done##
Opening file:
2018-04
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
key error
167
2844
1549
0

In [4]:
import numpy as np
import pandas as pd
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import subjectivity
from nltk.sentiment import SentimentAnalyzer
from nltk.sentiment.util import *

In [5]:
# Reading the saved data pickle file
df_stocks = pd.read_pickle('pickled_para.pkl')
df_stocks

,close,articles
2018-03-17 01:30:00,24946.51,
2018-03-20 01:30:00,24610.91,
2018-03-21 01:30:00,24727.27,
2018-03-22 01:30:00,24682.31,
2018-03-23 01:30:00,23957.89,
2018-03-24 01:30:00,23533.20,
2018-03-27 01:30:00,24202.60,
2018-03-28 01:30:00,23857.71,
2018-03-29 01:30:00,23848.42,
2018-03-30 01:30:00,24103.11,
2018-04-03 01:30:00,23644.19,". In Texas, Ted Cruz Is Facing an Unusual Chal..."
2018-04-04 01:30:00,24033.36,". $700,000 Homes in Washington, Pennsylvania a..."
2018-04-05 01:30:00,24264.30,". In Sparing Consumers Tariff Burden, Trump Hi..."
2018-04-06 01:30:00,24505.22,. Paperback Row. Listen to ‘The Daily’: Taking...
2018-04-07 01:30:00,23932.76,. Poison Gas Attack Reported by Syrian Anti-Go...
2018-04-10 01:30:00,23979.10,. Kansas and North Carolina State Named in New...
2018-04-11 01:30:00,24408.00,". Syria, FIFA, Royal Wedding: Your Wednesday B..."
2018-04-12 01:30:00,24189.45,". Syria, Russia, Facebook: Your Thursday Brief..."
2018-04-13 01:30:00,24483.05,". Wait, New Jersey Was Once Not Cool?. Is Your..."

In [6]:
df_stocks['prices'] = df_stocks['close'].apply(np.int64)
# selecting the prices and articles
df_stocks = df_stocks[['prices', 'articles']]

In [7]:
df_stocks['articles'] = df_stocks['articles'].map(lambda x: x.lstrip('.-'))

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [8]:
df_stocks
df = df_stocks[['prices']].copy()
df

                     prices
2018-03-17 01:30:00   24946
2018-03-20 01:30:00   24610
2018-03-21 01:30:00   24727
2018-03-22 01:30:00   24682
2018-03-23 01:30:00   23957
2018-03-24 01:30:00   23533
2018-03-27 01:30:00   24202
2018-03-28 01:30:00   23857
2018-03-29 01:30:00   23848
2018-03-30 01:30:00   24103
2018-04-03 01:30:00   23644
2018-04-04 01:30:00   24033
2018-04-05 01:30:00   24264
2018-04-06 01:30:00   24505
2018-04-07 01:30:00   23932
2018-04-10 01:30:00   23979
2018-04-11 01:30:00   24408
2018-04-12 01:30:00   24189
2018-04-13 01:30:00   24483

In [9]:
# Adding new columns to the data frame
df["compound"] = ''
df["neg"] = ''
df["neu"] = ''
df["pos"] = ''
df

                     prices compound neg neu pos
2018-03-17 01:30:00   24946
2018-03-20 01:30:00   24610
2018-03-21 01:30:00   24727
2018-03-22 01:30:00   24682
2018-03-23 01:30:00   23957
2018-03-24 01:30:00   23533
2018-03-27 01:30:00   24202
2018-03-28 01:30:00   23857
2018-03-29 01:30:00   23848
2018-03-30 01:30:00   24103
2018-04-03 01:30:00   23644
2018-04-04 01:30:00   24033
2018-04-05 01:30:00   24264
2018-04-06 01:30:00   24505
2018-04-07 01:30:00   23932
2018-04-10 01:30:00   23979
2018-04-11 01:30:00   24408
2018-04-12 01:30:00   24189
2018-04-13 01:30:00   24483

In [10]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import unicodedata
sid = SentimentIntensityAnalyzer()
for date, row in df_stocks.T.iteritems():
    try:
        sentence = unicodedata.normalize('NFKD', df_stocks.loc[date, 'articles'])
        ss = sid.polarity_scores(sentence)
        df.set_value(date, 'compound', ss['compound'])
        df.set_value(date, 'neg', ss['neg'])
        df.set_value(date, 'neu', ss['neu'])
        df.set_value(date, 'pos', ss['pos'])
    except TypeError:
        print (df_stocks.loc[date, 'articles'])
        print (date)

In [11]:
df

                     prices compound    neg    neu    pos
2018-03-17 01:30:00   24946        0      0      0      0
2018-03-20 01:30:00   24610        0      0      0      0
2018-03-21 01:30:00   24727        0      0      0      0
2018-03-22 01:30:00   24682        0      0      0      0
2018-03-23 01:30:00   23957        0      0      0      0
2018-03-24 01:30:00   23533        0      0      0      0
2018-03-27 01:30:00   24202        0      0      0      0
2018-03-28 01:30:00   23857        0      0      0      0
2018-03-29 01:30:00   23848        0      0      0      0
2018-03-30 01:30:00   24103        0      0      0      0
2018-04-03 01:30:00   23644   -0.998  0.128  0.789  0.083
2018-04-04 01:30:00   24033  -0.9965  0.118  0.803  0.079
2018-04-05 01:30:00   24264  -0.9995  0.144  0.791  0.065
2018-04-06 01:30:00   24505  -0.9985  0.135   0.79  0.075
2018-04-07 01:30:00   23932  -0.9954  0.152  0.759  0.089
2018-04-10 01:30:00   23979  -0.9867  0.142  0.732  0.126
2018-04-11 01:30:00   24408  -0.9916  0.102  0.814  0.085
2018-04-12 01:30:00   24189  -0.9985  0.116  0.815  0.068
2018-04-13 01:30:00   24483  -0.9986  0.113  0.827   0.06

In [12]:
#import time
#import datetime


test = df.ix[test_start_date:test_end_date]


##
#test_start_date = '2018-03-09'
#test_end_date = '2018-03-10'
test = df.ix[test_start_date:test_end_date]
  
##    
    
# Calculating the sentiment score
sentiment_score_list = []
for date, row in test.T.iteritems():
    sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
    #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
    sentiment_score_list.append(sentiment_score)
    numpy_df_test = np.asarray(sentiment_score_list)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """

In [13]:
numpy_df_test

NameError: name 'numpy_df_test' is not defined

In [ ]:
import pickle

filename = 'finalized_model_GSPC.sav'
loaded_model = pickle.load(open(filename, 'rb'))
#loaded_model.fit(numpy_df_test,test['prices'])   
result = loaded_model.predict(numpy_df_test)



print(result)

In [ ]:
ret = loaded_model.score(numpy_df_test,test['prices'])
print(ret)